import { useEffect, useMemo, useState } from 'react'
import { ArrowDownToLine, BarChart3, CalendarDays, CreditCard, IndianRupee, PackageSearch, TrendingDown, UsersRound } from 'lucide-react'
import { api, money } from './api'

function csvDownload(rows, filename) { const text=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n'); const blob=new Blob([text],{type:'text/csv;charset=utf-8'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=filename; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url) }
export default function HisaaboAnalyticsPanel() {
  const [invoices,setInvoices]=useState([]),[products,setProducts]=useState([]),[customers,setCustomers]=useState([]),[range,setRange]=useState('30d'),[loading,setLoading]=useState(true)
  useEffect(()=>{Promise.all([api.invoices({limit:100}),api.products({limit:100}),api.customers({limit:100})]).then(([i,p,c])=>{setInvoices(i.invoices||[]);setProducts(p.products||[]);setCustomers(c.customers||[])}).catch(()=>{}).finally(()=>setLoading(false))},[])
  const days=range==='7d'?7:range==='90d'?90:30,cutoff=Date.now()-days*86400000; const scoped=invoices.filter(i=>{const t=new Date(i.invoice_date).getTime();return Number.isFinite(t)&&t>=cutoff&&Number(i.invoice_status)!==1})
  const stats=useMemo(()=>({sales:scoped.reduce((s,i)=>s+Number(i.total_amount_paise||0),0),count:scoped.length,paid:scoped.filter(i=>Number(i.payment_status)===1).reduce((s,i)=>s+Number(i.total_amount_paise||0),0),pending:scoped.filter(i=>Number(i.payment_status)===0).reduce((s,i)=>s+Number(i.total_amount_paise||0),0),low:products.filter(p=>Number(p.stock_quantity)<=Number(p.reorder_level||0)).length}),[scoped,products])
  const reportRows=[['Invoice','Customer','Date','Total','Payment'],...scoped.map(i=>[i.invoice_number,i.customer_name||'Walk-in',i.invoice_date,money(i.total_amount_paise),({0:'Cash',1:'UPI',2:'Bank',3:'Credit',4:'Other'})[Number(i.payment_method)]||'Other'])]
  if(loading)return <div className="panel p-6 text-sm text-slate-500">Loading analytics…</div>
  return <div className="panel p-5 md:p-6"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-brand-500/10 text-brand-400"><BarChart3 size={20}/></div><div><h2 className="font-[Outfit] text-lg font-bold text-slate-100">Business overview</h2><p className="text-sm text-slate-500">Hisaabo-style sales, collections and inventory snapshot.</p></div></div><div className="flex flex-wrap gap-2"><div className="inline-flex rounded-lg border border-slate-800 bg-slate-950 p-0.5">{[['7d','7 days'],['30d','30 days'],['90d','90 days']].map(([v,l])=><button key={v} onClick={()=>setRange(v)} className={`rounded-md px-3 py-1.5 text-xs font-semibold ${range===v?'bg-brand-500/15 text-brand-300':'text-slate-500 hover:text-slate-200'}`}>{l}</button>)}</div><button className="btn-secondary text-xs" onClick={()=>csvDownload(reportRows,`sales-${range}.csv`)}><ArrowDownToLine size={15}/>Export CSV</button></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Mini label="Sales" value={money(stats.sales)} icon={IndianRupee}/><Mini label="Invoices" value={stats.count} icon={CreditCard}/><Mini label="Collected" value={money(stats.paid)} icon={TrendingDown}/><Mini label="Pending" value={money(stats.pending)} icon={CalendarDays}/><Mini label="Low stock" value={stats.low} icon={PackageSearch}/></div><div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-slate-800 bg-slate-950/40 p-4"><div className="flex items-center gap-2 text-sm font-semibold text-slate-200"><UsersRound size={16} className="text-amber-400"/>Customers</div><div className="mt-2 font-[Outfit] text-2xl font-extrabold text-slate-100">{customers.length}</div><div className="mt-1 text-xs text-slate-500">Active customer records</div></div><div className="rounded-2xl border border-slate-800 bg-slate-950/40 p-4"><div className="flex items-center gap-2 text-sm font-semibold text-slate-200"><PackageSearch size={16} className="text-blue-400"/>Inventory</div><div className="mt-2 font-[Outfit] text-2xl font-extrabold text-slate-100">{products.reduce((s,p)=>s+Number(p.stock_quantity||0),0)}</div><div className="mt-1 text-xs text-slate-500">Units currently in stock</div></div></div></div>
}
function Mini({label,value,icon:Icon}){return <div className="rounded-2xl border border-slate-800 bg-slate-950/40 p-4"><div className="flex items-center justify-between"><span className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</span><Icon size={16} className="text-slate-500"/></div><div className="mt-2 font-[Outfit] text-lg font-bold text-slate-100">{value}</div></div>}
